version: '3.5'

services:


  mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    command: --character-set-server=utf8 --collation-server=utf8_bin
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      zabbix-network:
        ipv4_address: 172.22.0.2
    restart: always

  zabbix-server:
    depends_on:
      - mysql
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=mysql
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    ports:
      - 10051:10051
    networks:
      zabbix-network:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-web:
    depends_on:
      - mysql
      - zabbix-server
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=America/Sao_Paulo
    ports:
      - 80:8080
    networks:
      zabbix-network:
        ipv4_address: 172.22.0.4
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: zabbix-grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      zabbix-network:
        ipv4_address: 172.22.0.5
    restart: always
  app:
    build: ./app
    ports:
      - "5000:5050"
    restart: always  

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1

volumes:
  mysql_data:
  grafana_data:
